/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { WelcomeMessage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WelcomeControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a random welcome message
     * Returns a random welcome message from the predefined list of greetings
     */
    getRandomWelcome(extraHttpRequestParams?: any): Observable<WelcomeMessage>;

}
